apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  # Webfrontend
  - containerPort: 32701
    hostPort: 8091
  # ApiService
  - containerPort: 32702
    hostPort: 8092
  # AspireDashboard UI
  - containerPort: 32703
    hostPort: 8093
  # AspireDashboard OTLP
  - containerPort: 32704
    hostPort: 8094
